name: wt
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  persistent_bottom_nav_bar: ^5.0.2
    


  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  assets:
    - lib/images/sharken.png
    - lib/images/rogo.png
    - lib/images/members.jpg

  uses-material-design: true
